---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistence-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
