apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: time-server-ingress-balancer
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  externalIPs:
    - 65.21.108.81
    - 65.21.57.112
  rules:
  - host: time.volnenko.ru
    http:
      paths:
      - path: /    
        pathType: Prefix    
        backend:
          service:
            name: time-server-service
            port:
              number: 80
