apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: time-server-ingress-balancer
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tomcat.volnenko.ru
    http:
      paths:
      - path: /    
        pathType: Prefix    
        backend:
          service:
            name: tomcat-service
            port:
              number: 80
  - host: time.volnenko.ru
    http:
      paths:
      - path: /    
        pathType: Prefix    
        backend:
          service:
            name: time-server-service
            port:
              number: 80
