---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gateway
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: tomcat.volnenko.ru
    http:
      paths:
      - backend:
          service:
            name: tomcat-service
            port:
              number: 8080
        pathType: ImplementationSpecific
  - host: time.volnenko.ru
    http:
      paths:
      - backend:
          service:
            name: time-server-service
            port:
              number: 8080
        pathType: ImplementationSpecific
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: ingress-gateway
  externalIPs:
    - 95.217.177.1

