---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gateway
spec:
  rules:
  - host: tomcat.volnenko.ru
    http:
      paths:
      - backend:
          service:
            name: tomcat-service
            port:
              number: 8080
        pathType: ImplementationSpecific
  - host: time.volnenko.ru
    http:
      paths:
      - backend:
          service:
            name: time-server-service
            port:
              number: 8080
        pathType: ImplementationSpecific
