apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-server-deployment
spec:
  selector:
    matchLabels:
      app: time-server
  replicas: 1
  template:
    metadata:
      labels:
        app: time-server
    spec:
      containers:
      - name: time-server
        image: volnenko/time-server:latest
        ports:
        - containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: time-server-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: time-server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: time-server-ingress
spec:
  rules:
    - host: time.volnenko.ru
      http:
        paths:
          - backend:
              serviceName: time-server-service
              servicePort: 8080
