---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server-deployment
  labels:
    app: simple-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-server
  template:
    metadata:
      labels:
        app: simple-server
    spec:
      containers:
        - name: simple-server
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 8080
          env:
            - name: PMA_HOST
              value: mysql
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-server-service
spec:
  type: NodePort
  selector:
    app: simple-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

